### ISSUE TITLE
CONTRIBUTING.md contains invalid email address: ccs-mod-docs@redhat.com

### ISSUE THREAD

**Issue by rolfedh** [redhat-documentation/modular-docs#105]
CONTRIBUTING.md tells users to send email to ccs-mod-docs@redhat.com Modular Documentation Project mailing list asking for access to the Modular Documentation Project. However, sending an email message to that address produces the following message
```
Message not delivered
--
Your message couldn't be delivered to ccs-mod-docs@redhat.com because the remote server is misconfigured. See technical details below for more information.

554 5.7.1 <ccs-mod-docs@redhat.com>: Recipient address rejected: Access denied
```

**Comment by adahms** [comment]
Hey @rolfedh - Thanks for raising this issue!

I have added you to the project now, so you should be able to submit PRs and interact with the project as needed, but I'd like to dig into the issue encountered a bit more as well.

Did you send that email from your RH address?

**Comment by adahms** [comment]
It has been a month since the last traffic on this issue, and given the comment above adding the user to this project, I will be closing this issue for now.

Rolfe - let me know if you continue to run into issues and we'll look into it.
