### ISSUE TITLE
Decide what subheadings to use in the procedure module and update the template

### ISSUE THREAD

**Issue by baruza** [redhat-documentation/modular-docs#11]
This issue includes several questions, I believe that for most of them we already came up with an answer, though. This issue should record the discussion and decisions in an open manner and track what changes should we done in the guide.

1) What subheading to use for the prerequisites section. I believe that we decided to use "Prerequisites". Any objections?

2) What subheading to use for the procedure itself. I think (from what I seen, that is is "Procedure") + is it a good idea to repeat the name of the procedure module in that title (for example Procedure: Changing the User Name)? Cons: duplication, Pros: possible better results when in searching results? Can someone who is in contact with JP Shermman check? (Nacia, Betty?)

3) What subheading to use for the additional details sections? I believe we decided to use "Additional Resources". Any objections?

4) Should we use the [discrete] tag for the subheadings so they don't show up in TOC? I believe that this is what we are already doing, but just want to confirm.

In addition, the guide should state why whatever we decide is recommended to follow (be consistent, cross-product reuse of modules, etc).

**Comment by asteflova** [comment]
1. Ack
2. Procedure as the subheading - ack.
Repeating the name of the procedure module - I'd prefer not to do that. Duplication is a big con for me. The Procedure subheading is typically very close to the module heading (often separated only by a short procedure intro), so I don't think repeating it would add much value.
3. Ack
4. Ack

**Comment by asteflova** [comment]
I sent https://github.com/redhat-documentation/modular-docs/pull/45 to propose a solution (based on a few conversations I took part in). The request was accepted, so I think we can close this issue.
