### ISSUE TITLE
nested vs leveloffset 

### ISSUE THREAD

**Issue by pwright** [redhat-documentation/modular-docs#112]
I have somehow got the impression that we *must* nest assemblies..
I'm reporting the following as a bug:

There's no mention of leveloffset in the reference guide, but  lots of discussion of nested assemblies.

**Comment by sterobin** [comment]
Discussed with @pwright in chat and addressed with PR #166

**Comment by pwright** [comment]
node https://raw.githubusercontent.com/redhat-documentation/modular-docs/master/modular-docs-manual/files/TEMPLATE_ASSEMBLY_a-collection-of-modules.adoc

**Comment by emmurphy1** [comment]
@adahms I've merged PR 166 which address this issue.
