### ISSUE TITLE
Files in simple-mod-guide-repo.zip don't meet standards

### ISSUE THREAD

**Issue by ncbaratta** [redhat-documentation/modular-docs#114]
In modular-docs/modular-docs-manual/files/simple-mod-guide-repo.zip we should update the files to include the proper filenaming and folder structures required by the new pantheon build tools.

**Comment by ncbaratta** [comment]
To clarify, the files in the zip are named things like module-a, module-b, assembly-1

Yet the rules are to have proc-,con-,ref, assembly- [FILENAME/TITLE] 

The same goes for the text here: https://redhat-documentation.github.io/modular-docs/#a-simple-example-of-a-modular-guide

**Comment by VladimirSlavik** [comment]
As an aside, it would be very useful to have these files available also here in the repository, so the zip archive could be generated.

**Comment by vikram-redhat** [comment]
As far as I know this rule is not final yet (https://github.com/redhat-documentation/modular-docs/issues/111#issue-560052066). Second, even when it does get final, the rule is optional. Teams can choose to go with either the file name option OR the attribute option within the files. The zip file is correct as per the last time these rules were changed and made final.

**Comment by sterobin** [comment]
@ncbaratta This is being addressed in PR #120 . Pinging you there as part of the reviewers.

**Comment by VladimirSlavik** [comment]
@sterobin I don't really care that much, it's really up to you. My reasoning was along these lines:
- I don't want to bother with unpacking and repacking, so perhaps that is how others feel about it too. In other words, lower friction for changes.
- If the example repo is part of the real repo, people can browse the structure online without cloning.
- So long as it is only text, I would not consider it large in terms of download size, the issue would be with cognitive load - and then it will have its own directory so it's easy to reason about.

But that really is just one opinion :)

**Comment by sterobin** [comment]
Resolved as part of #120 . Closing.
