### ISSUE TITLE
Module re-use section incorrectly directs use of hyphen for appending  {context}

### ISSUE THREAD

**Issue by cbudz** [redhat-documentation/modular-docs#115]
https://redhat-documentation.github.io/modular-docs/#reusing-modules

" add the {context} suffix with a hyphen to the anchor name in the format "

When implemented {context} is appended to the anchor name using an underscore.

**Comment by sterobin** [comment]
@cbudz , right. That's supposed to say to use an underscore. That's how I had originally written that section and lately had re-suggested that. That has been changed and re-changed times over. Should be hyphenated all around, except before context: `proc-doing-something_{context}`. The prefix is also under consideration by @adahms, as you know. Hopefully this is circling to a conclusive decision.

**Comment by cbudz** [comment]
@sterobin thanks for the response on this. I'll keep an eye out for updates.

**Comment by emmurphy1** [comment]
This issue was resolved in https://github.com/redhat-documentation/modular-docs/pull/121 and the changes incorporated in the Reference Manual.
