### ISSUE TITLE
Clear definition of assembly titles is missing

### ISSUE THREAD

**Issue by mjahoda** [redhat-documentation/modular-docs#118]
There is no clear definition of assembly titles. You have to guess it from the examples.

https://redhat-documentation.github.io/modular-docs/#forming-assemblies

**Comment by sterobin** [comment]
Nacia is on this and will be assigned shortly once she is part of the org.

**Comment by mjahoda** [comment]
Hello @kalexand-rh

What is the current status of this addition? Can I help you with finishing this task?

Thank you.

**Comment by mjahoda** [comment]
Resolved by merging https://github.com/redhat-documentation/modular-docs/pull/192
