### ISSUE TITLE
Are modules required in all assembies

### ISSUE THREAD

**Issue by mburke5678** [redhat-documentation/modular-docs#122]
The _Modular Documentation Reference Guide_ seems to suggest that assemblies **must** have a module:  _The **required** parts of an assembly are the introduction and **modules**._  (emphasis added) [1]
However, there seem to be times where a module is not necessary for understanding the content. For example, I have this topic that doesn't seem that it would help to have a module. All the information can be contained in the assembly; a module seems superfluous. [2]

[1] https://redhat-documentation.github.io/modular-docs/#assembly-guidelines
[2] https://github.com/openshift/openshift-docs/pull/23502/files#diff-cbc6ad36f690e81275dd6a5cc70ebba7

**Comment by VladimirSlavik** [comment]
No longer a writer, but: That looks like a concept or reference module to me, not an assembly. I always thought an assembly has a minimal intro text, and the bulk of content is in modules.

**Comment by emmurphy1** [comment]
@mburke5678 Yes, an assembly must include at least one module. The purpose of an assembly is to group related modules together with include statements. It was never the intent that an assembly be published without a module even though this is possible.

**Comment by emmurphy1** [comment]
This decision is recorded in the [Flexible Customer Content Decision Register](https://docs.engineering.redhat.com/pages/viewpage.action?spaceKey=FCCADOPT&title=Decision+Register), decision D12.
