### ISSUE TITLE
Headings in templates & guide should be sentence case

### ISSUE THREAD

**Issue by ncbaratta** [redhat-documentation/modular-docs#133]
A few years ago a decision was made in CCS that all headings should be sentence case. We should follow that guideline in this guide and in the templates we provide.

**Comment by emmurphy1** [comment]
Please review the following PR where I fixed the headings and subheadings:
https://github.com/redhat-documentation/modular-docs/pull/189

**Comment by emmurphy1** [comment]
@adahms no need to add this to the decision register.
