### ISSUE TITLE
Provide templates for required master.adoc, attributes.adoc, and master-docinfo.xml files for PV1 and PV2

### ISSUE THREAD

**Issue by spank50** [redhat-documentation/modular-docs#146]
To build a document using our preview tools, you need a master.adoc and (usually) an attributes.adoc file. The master-docinfo.xml file is required to publish with Pantheon V1 and certain of its content must match Pantheon descriptors. The XML file might also be required for Pantheon V2 publishing.

Provide templates for each required file with descriptions of required elements and other allowed elements.

User story:
As a CCS toolchain user, I want to create the master.adoc, attributes.adoc, and master-docinfo.xml files that will successfully build previews with bccutil, ccuilt, asciidoctor and will build Pantheon PV1 and PV2 preview and stage versions of a document.

**Comment by rkratky** [comment]
@spank50, thanks for the suggestion. While the files you're listing are important parts of Red Hat documentation teams' work flows, they are not in any way related to the modular documentation concept. As such, the mod docs guidelines are not the place to describe them. Likewise, Pantheon considerations are directly tied to the Red Hat publication toolchain and have nothing to do with modular docs (and you can find `docinfo.xml` requirements described in internal Pantheon docs).

That said, thanks to @sterobin, this repository contains a [mod-doc-repo-example](https://github.com/redhat-documentation/modular-docs/tree/mod-doc-repo-example) branch, which provides a ready-to-use example of a directory structure and file templates (incl. `master.adoc` and `docinfo.xml` files) that can be used when publishing using Pantheon.
