### ISSUE TITLE
Clarify that the "Prerequisites" heading is always plural

### ISSUE THREAD

**Issue by bergerhoffer** [redhat-documentation/modular-docs#153]
Unless I'm mistaken, the "Prerequisites" heading should always be plural, even if there is only one prereq listed. If this is correct, can we clarify that, either in the guide or the templates?

I've recently seen a few instances in our repo where people were using "Prerequisite" singular when there was only one listed.

**Comment by emmurphy1** [comment]
Yes, that is correct Andrea. Always plural and a bulleted list even if that list only has one item. Perhaps we need to add a comment about that in the templates.

**Comment by IngridT1** [comment]
Perhaps the templates and the style guide?

**Comment by bergerhoffer** [comment]
> Perhaps the templates and the style guide?

I don't think it necessarily needs to be in the style guide, as long as it's spelled out in the mod docs guide or templates (procedure and assembly).

**Comment by mikemckiernan** [comment]
A small update make sense to me.

**Comment by bergerhoffer** [comment]
Closing this issue since @mikemckiernan submitted an update. Thanks all!
