### ISSUE TITLE
Inconsistent module IDs in the procedure module template

### ISSUE THREAD

**Issue by yetanothertw** [redhat-documentation/modular-docs#155]
In the procedure module template [1], in the "Base the file name and the ID on the module title. For example:" section (block comment), the recommendation for the module ID format is (line 8):
* ID: [id="doing-procedure-a_{context}"]  

and then after this section (block comment) the example uses the following ID (line 14):
[id="proc-doing-one-procedure_{context}"]

I think they should both be [id="proc-doing-one-procedure_{context}"], so line 8 needs to be updated.

[1] https://raw.githubusercontent.com/redhat-documentation/modular-docs/master/modular-docs-manual/files/TEMPLATE_PROCEDURE_doing-one-procedure.adoc

**Comment by yetanothertw** [comment]
@emmurphy1 @adahms @sterobin just making sure you're aware of this issue, that is if you can validate that it is an issue indeed.
Many thanks

**Comment by adahms** [comment]
Thanks for raising this issue, @yetanothertw!

A review of the module suggests the examples are consistent with themselves - i.e. the context and title in the top example match one another, and the context and title in the actual module piece match one another - but are not consistent with one another.

@emmurphy1 @sterobin - would making these two sets the same reduce some confusion?

**Comment by emmurphy1** [comment]
https://github.com/redhat-documentation/modular-docs/pull/163

**Comment by yetanothertw** [comment]
Thanks, Emily!

**Comment by emmurphy1** [comment]
@adahms this issue was updated in PR 164, and merged.
