### ISSUE TITLE
Pantheon 2 creates its own labels for "Additional resources" in modules vs assemblies. That should be dealt with here.

### ISSUE THREAD

**Issue by stoobie** [redhat-documentation/modular-docs#158]
Previously, Pantheon 2 didn’t distinguish between additional resources sections for modules and assemblies as clearly as it could have, creating some confusion among readers. Engineering has now improved the appearance of these sections to delineate them as seen in the following assembly:
https://access.redhat.com/documentation/en-us/red_hat_openshift_api_management/1/guide/53dfb804-2038-4545-b917-2cb01a09ef98

So now for modules we have by default .Additional resources is hidden and you see a link to show it:
![image](https://user-images.githubusercontent.com/39279277/110796877-20f12a00-8281-11eb-90f4-207d0ef687e3.png)

And when you expand it you get this:

![image](https://user-images.githubusercontent.com/39279277/110796723-f1422200-8280-11eb-932b-78edf3dce94c.png)

And for assemblies we have this (expanded by default):

![image](https://user-images.githubusercontent.com/39279277/110796771-01f29800-8281-11eb-9008-1436a846ea37.png)

First of all, **Content related to this topic|guide** and **Additional resources** together is redundant and a bit confusing.

Secondly, I propose that we adopt the new wording in place of Additional resources and instead use something like **Content related to this topic** for modules and **Content related to this guide|section** for top-level assemblies|nested assemblies.

**Comment by stoobie** [comment]
The wording for assemblies is tricky, because an assembly can be either a guide or a section within a guide, so you can't always say **Content related to this guide**.

**Comment by emmurphy1** [comment]
@stoobie, Additional resources can be Next steps, or some other label that the writer determines. Therefore, having the label under Content related to this topic/guide makes sense. We discussed it at the Modular Documentation Review Board and unanimously decided against this change.

**Comment by stoobie** [comment]
@emmurphy1 OK, so closing the issue.
