### ISSUE TITLE
Procedure module template link?

### ISSUE THREAD

**Issue by max-cx** [redhat-documentation/modular-docs#194]
I can't find a link to
https://github.com/redhat-documentation/modular-docs/blob/master/modular-docs-manual/files/TEMPLATE_PROCEDURE_doing-one-procedure.adoc
in
https://redhat-documentation.github.io/modular-docs/#concept-module-guidelines

The concept module template and the reference module template are linked to from the respective sections, but the section about the procedure module (which is the most important module type) doesn't seem to contain any link to the template file (link above).

**Comment by mjahoda** [comment]
@max-cx You're right, thank you for catching this. The following PR should address the problem:
https://github.com/redhat-documentation/modular-docs/pull/195/files
