### ISSUE TITLE
Remove module prefixes from IDs in the templates

### ISSUE THREAD

**Issue by mjahoda** [redhat-documentation/modular-docs#198]
The current templates contain module prefixes (proc_, con_, ref_) in anchors (IDs). This has no benefits, only drawbacks (more characters, worse readability, worse URLs).

Related to the newdoc issue: https://github.com/redhat-documentation/newdoc/issues/21

**Comment by emmurphy1** [comment]
This change was approved by the Steering Committee. @mjahoda please create an MR to update the templates.

**Comment by mjahoda** [comment]
While I'm on it, can I also remove the `[role="_abstract"]` line from the template files?

**Comment by emmurphy1** [comment]
I see that you changed the  dash to an underscore for the file name, for all of the templates:
* file name: con-my-concept-module-a.adoc
* file name: con_my-concept-module-a.adoc
While I don't have strong feelings about either one, it is a change that I don't think is necessary or particularly advantageous. When writers who have been following the current convention (con-, proc-, ref-) see this change it could cause confusion.

**Comment by emmurphy1** [comment]
@mjahoda yes, please remove the [role="_abstract"] tag.
