### ISSUE TITLE
Modules and assemblies -- review guidelines, examples, write a definition

### ISSUE THREAD

**Issue by asteflova** [redhat-documentation/modular-docs#2]
Proposed structure of the section about procedure modules: _Creating Procedure Modules_ (assembly):

1. _Definition: a ‘do’ module_ (concept module)
- As short as possible
- Must include that a procedure module is not just steps
EDIT: ALL DONE: Done for procedure modules, concept modules, reference modules, and assemblies.
2. _Guidelines_ (concept module)
- Review the current guidelines as a group
EDIT: ALL DONE: Done for procedure modules, concept modules, reference modules, and assemblies.
3. _Additional Resources_
- Link to templates
EDIT: ALL DONE: Done for procedure modules, concept modules, reference modules, and assemblies.
- Link to examples (Each team member nominates 1 or 2 (?), we pick the best examples.)
EDIT: Done.

This issue does not track changes to the templates. See https://github.com/redhat-documentation/modular-docs/issues/12 and https://github.com/redhat-documentation/modular-docs/issues/11.

**Comment by asteflova** [comment]
PR for the procedure module accepted. I submitted two more for the concept module and assembly.

**Comment by asteflova** [comment]
We have new issues for some changes to the templates (https://github.com/redhat-documentation/modular-docs/issues/12 and https://github.com/redhat-documentation/modular-docs/issues/11), so I'll update the description of this issue a bit.

**Comment by asteflova** [comment]
I edited the first comment to note the progress on this issue.

**Comment by nengard** [comment]
Here is a procedure example that might be good to share:

https://redhat-documentation.github.io/amq7/index.html#configure-git

**Comment by baruza** [comment]
Hi Aneta, the Ceph Container Guide is written in modular manner:

https://gitlab.cee.redhat.com/red-hat-ceph-storage-documentation/doc-Red_Hat_Ceph_Storage_3-Container_Guide/tree/master

https://doc-stage.usersys.redhat.com/documentation/en-us/red_hat_ceph_storage/3/html-single/container_guide/

I hope you can find some good examples there. We also reusing some of the modules in the Installation Guide. 

Or you can check the Ceph File System guide:

https://gitlab.cee.redhat.com/red-hat-ceph-storage-documentation/doc-Red_Hat_Ceph_Storage_3-File_System_Guide/tree/master

https://doc-stage.usersys.redhat.com/documentation/en-us/red_hat_ceph_storage/3/html-single/ceph_file_system_guide/

Hope that helps!

**Comment by asteflova** [comment]
Concept module:
1.2. Available Container Images https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/using_containerized_identity_management_services/overview-of-the-containerized-ipa-services#overview-containers-available-container-images

Procedure modules:
6.2. Enrolling to an Identity Management Domain Using an SSSD Container https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/using_containerized_identity_management_services/configuring-the-sssd-container-to-provide-identity-and-authentication-services-on-atomic-host#sssd-services-on-host-enrolling-to-an-ipa-domain-using-an-sssd-container
10.1. Uninstalling an SSSD Container Enrolled in an Identity Management Domain https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/using_containerized_identity_management_services/uninstalling-sssd-containers#uninstalling-sssd-containers-uninstalling-an-sssd-container-enrolled-in-an-ipa-domain

**Comment by bhardesty** [comment]
I'm including a few assorted examples that might demonstrate some different or unique ways to use assemblies and modules. Feel free to use or disgard.

Assembly with "choices" (in this case, there are multiple options for accomplishing the user goal):
https://access.redhat.com/documentation/en-us/red_hat_jboss_amq/7.0/html-single/using_amq_interconnect/#securing_incoming_connections

A simple assembly with two procedures:
https://access.redhat.com/documentation/en-us/red_hat_jboss_amq/7.0/html-single/using_amq_interconnect/#routing_messages_in_a_peer_to_peer_configuration

Concept and procedures for CLI commands:
https://access.redhat.com/documentation/en-us/red_hat_jboss_amq/7.0/html-single/using_amq_interconnect/#monitoring_amq_interconnect_using_literal_qdstat_literal

An alternate method of using a reference module to present a list of (mostly) single-step procedures you can do with a CLI command:
https://access.redhat.com/documentation/en-us/red_hat_jboss_amq/7.0/html-single/using_amq_interconnect/#managing_network_connections

**Comment by asteflova** [comment]
We're getting closer! The last thing to do before we can close this issue is add examples, I'm working on that.

**Comment by asteflova** [comment]
Examples added. That should be all for this issue.
