### ISSUE TITLE
Add/update sections on anchors, files, and module reuse so we can standardize

### ISSUE THREAD

**Issue by sterobin** [redhat-documentation/modular-docs#20]
See my [pull request](https://github.com/redhat-documentation/modular-docs/pull/19) for details. I made additions and changes per my presentation and subsequent team discussion on standardizing anchor names, file names, and document attributes to enable content reuse and instill consistency across CCS.

**Comment by ritz303** [comment]
Closing this issue.  It was resolved by pull request #30.
