### ISSUE TITLE
Users no longer have a link to the procedure template

### ISSUE THREAD

**Issue by rolfedh** [redhat-documentation/modular-docs#204]
The [Creating Concept Modules](https://redhat-documentation.github.io/modular-docs/#creating-concept-modules) and [Creating reference modules](https://redhat-documentation.github.io/modular-docs/#creating-reference-modules) sections both have "additional resources" sections that link to the related templates:
- Concept [Additional resources](https://redhat-documentation.github.io/modular-docs/#_additional_resources)
- Reference - [Additional resources](https://redhat-documentation.github.io/modular-docs/#_additional_resources_2)

However, [3.1.2. Procedure modules](https://redhat-documentation.github.io/modular-docs/#con-creating-procedure-modules_writing-mod-docs) no longer has such a section or link.

**Comment by rolfedh** [comment]
I see that `modular-docs-manual/content/topics/creating_procedure_modules.adoc` on the master branch contains this "missing" information:

```
== Additional resources

* Download the link:https://github.com/redhat-documentation/modular-docs/blob/master/modular-docs-manual/files/TEMPLATE_PROCEDURE_doing-one-procedure.adoc[procedure module template (adoc file)] for new projects.
* For real-world examples of procedure modules, see <<modular-docs-procedure-examples>>.
````

**Comment by rolfedh** [comment]
[The published doc](https://redhat-documentation.github.io/modular-docs/#con-creating-procedure-modules_writing-mod-docs) doesn't reflect what's in the repo. 
We probably need to rebuild and publish the latest changes.

**Comment by rolfedh** [comment]
@rkratky: @emmurphy1 just mentioned you're solving this issue. You're welcome to close this issue.

**Comment by emmurphy1** [comment]
The reference guide has been updated:
https://redhat-documentation.github.io/modular-docs/#con-creating-procedure-modules_writing-mod-docs
