### ISSUE TITLE
ccs-mod-docs mailing list not public

### ISSUE THREAD

**Issue by rkratky** [redhat-documentation/modular-docs#22]
The repo's readme file points to a non-public mailing list:
```
Any Questions?
Send an email to our mailing list (ccs-mod-docs@redhat.com).
```
The reference should be removed, or the list opened.

**Comment by ritz303** [comment]
Updated the README.md file.
[Commit](https://github.com/redhat-documentation/modular-docs/commit/dd29c2b614b9bae0b9d1f7650a8d96612a961978)
