### ISSUE TITLE
Clarify 'Writing Additional Resources'

### ISSUE THREAD

**Issue by asteflova** [redhat-documentation/modular-docs#28]
With additional resources (in modules and assemblies), we definitely want to avoid writers adding resources just for the sake of having them. Additional Resources should always link to relevant resources only.

Right now, this is what we have in the manual:

~~~~
Writing Additional Resources

The additional resources list links to other material closely related to the contents of the concept module: other documentation resources (such as assemblies or modules), instructional videos, labs, and similar resources.

Focus on relevant resources that are likely to be of immediate interest to the user. Do not list every resource that could conceivably be related.
~~~~

**Comment by finp** [comment]
I'm not  sure how this could be clearer? maybe:

Focus on relevant resources that are likely to be of immediate interest to the user. Do not list resources for completeness.

**Comment by mishaone** [comment]
+1 the second line seems to convey that links should be added only if necessary. Perhaps something about how links are optional?

**Comment by finp** [comment]
what do people think of:

```
Writing Additional Resources

The optional additional resources list links to other material closely related to the contents of the <type>  module, for example, other documentation resources, instructional videos, or labs.

Focus on relevant resources that are likely to be of immediate interest to the user. Do not list resources for completeness.
```
NOTE: Similar text appears for con,proc, and assembly modules, I'm assuming we'd change all 3 and <type> would change for each instance

**Comment by ChristyWatkins** [comment]
Closing this with the info provided in PR 70
