### ISSUE TITLE
Modular Docs should recommend the structure of all new repos

### ISSUE THREAD

**Issue by vikram-redhat** [redhat-documentation/modular-docs#49]
This issue requires that modular docs mandate that we use the same structure for all new repositories, and have all older repositories plan on migrating to the new structure.

Although the guidelines recommend how we create modules and assemblies including how to name them, it makes no requirements on the way these are structured into a repository. It also doesn't provide any guidelines on how folders should be named, where you should keep the modules and assemblies, how to handle nested modules (if any), location of variables, symbolic links and images.

All this is required to make sure that the tooling team has a consistent repository structure to deal with instead of creating workarounds for every edge case.

This should be mandatory for every new repository.

**Comment by vikram-redhat** [comment]
@ritz303 @ChristyWatkins @rkratky  - thoughts on this issue?

**Comment by rkratky** [comment]
@vikram-redhat I'm a bit hesitant to mandate same repo structure and naming for every docs repo. Perhaps we could work with the tooling team to define a set of parameters that they would need and then mandate the inclusion of a config file in each repo that would define the mapping of these parameters to whatever structure the particular team had adopted.

That way, trhe tooling team wouldn't need to create workarounds for a zillion edge cases, and, at the same time, docs teams wouldn't be pressured into using a structure and/or naming conventions that could potentially make their life more complicated.

WDYT?

**Comment by vikram-redhat** [comment]
@rkratky - I think that would work. I prefer that we move to a standard structure, but I realize that it is not always in our control. Before we go too overboard with different structures, we really need the tooling team to weigh in here and let us know what is or isn't possible.

**Comment by vikram-redhat** [comment]
@ritz303 - I don't think that is the same structure. Mod docs implementation will require updated structure information.

**Comment by ncbaratta** [comment]
I'm a bit late to the discussion here, but mandating directory structure won't work for those of us working in the upstream. We need to stay flexible in how we organize and name our files so that we can collaborate with our communities.

**Comment by vikram-redhat** [comment]
Hey @ncbaratta - aren't these modular docs guidelines for RH owned docs? That is, we are not requiring upstream to conform to these guidelines, so there is no question around us using these guidelines to make them change their repo structures?

**Comment by rkratky** [comment]
Correct, @vikram-redhat, but when working with upstream, it's much more efficient to have the same (or at least similar) structure in both upstream and downstream. The act of downstreaming then has a much smaller overhead.

Anyway, I would again point to my earlier [comment](#issuecomment-379171179): As long as we agree on a config mapping, repo structures can be divergent. Our tooling would find all content based on the configuration values.

**Comment by rkratky** [comment]
> so you are saying it is much more efficient to have the same structure in both upstream and downstream. @ncbaratta is saying that we can't mandate that

@vikram-redhat You're misunderstanding :)

When working with upstream, we mimic their structure in downstream. Therefore, we have the same structure, which makes collaboration & downstreaming easier. And we cannot adopt a standardized structure for downstream because we would either diverge from upstream or need to force upstream into something they don't want.

**Comment by ncbaratta** [comment]
Thanks, @rkratky for clarifying my comments!!  I agree with you on having a defined config mapping so that our directories can diverge if necessary.

**Comment by finp** [comment]
Is this in scope for this project?
I think it's a valuable discussion, but may not be easily resolved for all groups.
Could or should we move this discussion to the wiki part of this repo? (which I think is currently disabled)

**Comment by tylerkelly13** [comment]
Updated title based on discussion (and chat with @vikram-redhat).

The example of [a simple modular guide](https://redhat-documentation.github.io/modular-docs/#a-simple-example-of-a-modular-guide) looks good, although:
- large guides (assembly of assemblies) are something I think we are moving away from in Red Hat, so the `master.adoc` would be irrelevant.
- each guide would need to be in it's own folder for the Red Hat build system to work (at this time) as the assembly needs to be named `master.adoc` and there needs to be a `master-docinfo.xml` alongside it. 

```
Long-term
.
├── attributes.adoc <-- File with attributes for the whole repo.
├── assembly-1.adoc <-- Assembly files with include statements for modules.
├── assembly-2.adoc
├── images
│   ├── image1.png
│   ├── image2.png
│   └── image3.png
└── modules <-- Directory for modules.
    ├── module-a.adoc <-- Module files.
    ├── module-b.adoc
    ├── module-c.adoc
    └── module-d.adoc

Short-term 
(not required for asciidoctor and asciibinder users, currently used in some Red Hat docs repos)
.
├── attributes.adoc <-- File with attributes for the whole repo.
├── assembly-1
│   ├── master.adoc
│   ├── master-docinfo.xml
│   ├── images/   <-- symlink to modules directory (`ln -s ../images images`)
│   └── modules/  <-- symlink to modules directory (`ln -s ../modules modules`)
├── assembly-2
│   ├── master.adoc
│   ├── master-docinfo.xml
│   ├── images/
│   └── modules/
├── images
│   ├── image1.png
│   ├── image2.png
│   └── image3.png
└── modules <-- Directory for modules.
    ├── module-a.adoc <-- Module files.
    ├── module-b.adoc
    ├── module-c.adoc
    └── module-d.adoc
```

**Comment by finp** [comment]
It's unlikely that AeroGear docs will correspond with any prescribed layout, so follow up question is:
"Will symlinks be supported by RH tooling" ?

**Comment by ncbaratta** [comment]
@finp I don't think we should ask questions about the tools, but instead, make sure that the tools can work with our docs.  So I'd say, we need the tools to work with symlinks (at least my projects do).

**Comment by ChristyWatkins** [comment]
Tooling team has a draft of a proposed structure to review. Documentation for Aura should contain the proposed structure: https://gitlab.cee.redhat.com/ccs-tools/aura/wikis/home

**Comment by adahms** [comment]
Hi all - some time has gone by since this thread was initially started, and discussion around tooling has now shown that there is a high degree of flexibility as to how things are structured.

The Modular Documentation Reference Guide provides an example of a directory structure for a sample guide, the advice for which is sound and is likely the greatest solid advice we can give at this time.

I am in favor of closing this issue within its current scope, but I think we'll have an opportunity to tackle something like this again in the future as the tooling work progresses.

Unless there are any objections, I will close this at the end of the week.

**Comment by emmurphy1** [comment]
I agree, Andrew. I would also like to mention that @sterobin will be conducting [Creating Modular Documentation Repositories](https://learning.redhat.com/course/view.php?id=1980) workshops starting this month. I imagine interesting ideas and challenges will result.

**Comment by adahms** [comment]
Thanks @emmurphy1!

As mentioned above, I'll close this issue now, but we can always come back to this topic and investigate it further if needed.
