### ISSUE TITLE
Suggestion: Add ascii-doc source code for the rendered examples

### ISSUE THREAD

**Issue by jenmalloy** [redhat-documentation/modular-docs#53]
While the template examples and rendered examples are nice to see, it would also be nice to be able to see the ascii-doc source of the rendered examples. (Since the guide is publicly available, the examples would need to be upstream code examples most likely. )
As a writer, I would find this very useful and helpful.

**Comment by ritz303** [comment]
@jenmalloy : Sorry for the delay in responding.  I like the idea.  Currently, all module examples point to the Customer Portal, which is rendering source from internal Red Hat GitLab repositories.  I don't think the public has access to view these GitLab repositories.  We could copy those modules from GitLab to GitHub, and then show the AsciiDoc source from the GitHub copy.  You could update the content in [Appendix B](https://redhat-documentation.github.io/modular-docs/#appendix-examples).

Also, something for us to consider, is removing some of these older examples and putting in new examples that conform to our standard module [templates](https://github.com/redhat-documentation/modular-docs/tree/master/modular-docs-manual/files).  Some of these examples were written before the module templates were well established, but I think that is a bigger discussion, outside the scope of this request.

We you get some time, could you please submit a pull request for your suggestion.  I'm looking forward to seeing your pull request.

**Comment by finp** [comment]
How about:
All future examples should include source code.

( I know that some of the examples listed would not conform to the current standards, therefore we should not publish the source for those examples )

**Comment by adahms** [comment]
@jenmalloy - Just following up on some of the open issues against the templates labelled as 'help wanted' and saw this one.

Looks like we have the go ahead with the proposed changes here - is this something you would have the time to make some progress on, or are there any blockers we might be able to help with?

**Comment by jenmalloy** [comment]
@adahms Yes, I'm happy to contribute some examples. Will spin up a PR and we can iterate on it. Thanks!

**Comment by jenmalloy** [comment]
PR: https://github.com/redhat-documentation/modular-docs/pull/90

**Comment by kalexand-rh** [comment]
#90 has been merged. Closing.
