### ISSUE TITLE
Consider renaming directory for the templates

### ISSUE THREAD

**Issue by tanberry** [redhat-documentation/modular-docs#55]
I had a hard time finding the templates; would be great if the directory that contains the templates was actually named '/templates." Thanks!

**Comment by ncbaratta** [comment]
I agree with this.

**Comment by ritz303** [comment]
@tanberry : Thanks for the feedback!  As not to break existing links to the template from other places, I've added a symbolic link to the root of this repo.  Hopefully, that will make them easier to find when people come to the mod doc ref guide project page.

**Comment by ritz303** [comment]
@tanberry : Sorry, I just noticed that symbolic link didn't work the way I thought it would.  I'll have to rethink that.

**Comment by ritz303** [comment]
@tanberry : Okay, I got it figured out.  You can now view the mod templates straight from the root of repo, under the templates directory.

**Comment by ritz303** [comment]
@tanberry : Sorry once again, the symbolic links are not working like I thought.  I'm trying not to break all the other docs that link to the templates.  I'm going to have rethink this approach.

**Comment by finp** [comment]
@tanberry I'm wondering about the user path here:
1. If you've cloned the repo and are looking thru the files the symlink idea will work
2. If you're browsing github, symlinks won't work

How about
* create the symlinks for 'local development'
* Direct all users browsing github to https://redhat-documentation.github.io/modular-docs/
(that should be top of the  https://github.com/redhat-documentation/modular-docs page anyway, @ritz303  can you add that)

This is not ideal, but might have avoided @tanberry problem as stated

**Comment by tylerkelly13** [comment]
### Workaround.
Prerequisite:
- Have the mod docs repository cloned to your local disk.

On a command line:
1. Navigate to a convenient location (such as your home directory).
1. Create a symbolic link to the templates folder:
    ` $ ln -s <mod_docs_root_directory>/modular-docs-manual/files/ module_templates`
  For example:
    ` $ ln -s ~/Documents/modular-docs/modular-docs-manual/files/ module_templates`

Alternatively, use alias in your .bashrc file, such as:
    `alias procmod='cp ~/Documents/modular-docs/modular-docs-manual/files/TEMPLATE_PROCEDURE_doing-one-procedure.adoc $(pwd)'`
Creating a copy of the file in your current directory using the alias.

**Comment by finp** [comment]
+1 for add sym links,
-1 for editing .bashrc ;~)

**Comment by ritz303** [comment]
I've added the Mod Doc Ref Guide link to the top of the project home page, and add a link to the module template files.
