### ISSUE TITLE
Suggestions for template improvements: mostly ID-related

### ISSUE THREAD

**Issue by jlprevatt** [redhat-documentation/modular-docs#58]
The information about IDs in the templates can be confusing, at least for AsciiDoc novices. 

Here are a few suggestions for improvements:

- The [id='my-concept-module-a'] does not match the [id='concept-explanation-{context}']. I think it would be more effective for both examples to match...right now the syntax is too different.
- The education provides a best practice/recommendation of a prefix for file names (con_, etc), and the template says the ID should match. Therefore, the best practice should be reflected in the template. The prefix should be used for the filename and ID. (Even if you note that it is best practice, follow what your library does, etc.)
- I think it would be better to get rid of the "my-xyz..." as an example and using some more real examples, such as "what-is-foo" or "starting-the-foo" or "foo-parameters." Using a name that is more real for each module type is a simple reminder of what that module's focus should be and how the module title should be worded.
- For someone who has not been working in AsciiDoc yet, I wasn't sure how to interpret the {context} right away--so it took a few moments to process. That's another place where a "real" ID example could help the writers less familiar with AsciiDoc realize that the {context} is code that stays (not some kind of variable to replace): [id='con_what-is-foo-{context}']. For newbies, it would also probably be better to explain it a bit more: "The context attribute (coded as "-{context}" at the end of the ID string) is included in every ID...." or something similar.

**Comment by tylerkelly13** [comment]
@jlprevatt 

1. Your first point has been/is being discussed in issue #44 and could be resolved by pull request #67. `_{context}` added to examples.
2. The second point has been/is being discussed in issue #25 and could be resolved by #61. Prefixes are likely to be eliminated).
3. [The examples in the guide](https://redhat-documentation.github.io/modular-docs/#anchor-and-file-names) seem to have been made clearer? 

4. Your last point, yep it could be clearer, if you have some idea of where this improvement should be made in the document (maybe somewhere in [Forming Assemblies](https://redhat-documentation.github.io/modular-docs/#forming-assemblies)) feel free to add a pull request with your suggested change (i'll add a 'help wanted' label, just in case you don't have time).

NOTE: help needed, point 4^

**Comment by jlprevatt** [comment]
One comment after a quick skim of your reply....
Your answers refer several times to the examples in the guide. My comments were addressing the templates that are linked to from the guide. If changes have been made to the guide, but the templates still have the things that I say will be confusing to AsciiDoc novices, then I think the widening mismatch between the guide and the templates will be even more confusing.
