### ISSUE TITLE
Write up an explanation of parametrized IDs in modular docs

### ISSUE THREAD

**Issue by asteflova** [redhat-documentation/modular-docs#6]
- (Some) writers don’t understand the need for [#id-{parameters}].
- The mod docs initiative has been asked (by the AsciiDoc Mark-up Conventions init.) to provide a doc that would explain the benefits of this approach and how it works.

**Comment by ritz303** [comment]
My goal is to have a draft of this content ready for review by the end of August.

**Comment by ritz303** [comment]
Submitted a [pull request](https://github.com/redhat-documentation/modular-docs/pull/10) to have my rough draft reviewed by the team.
