### ISSUE TITLE
Add Optional sections to procedures modules: "Results" and "Next Steps"

### ISSUE THREAD

**Issue by tylerkelly13** [redhat-documentation/modular-docs#68]
The optional sections of the procedure template: "Results" and "Next Steps" could be added to Procedure Template and [Modular Docs Guide](https://redhat-documentation.github.io/modular-docs/#creating-procedure-modules).
I propose that we add both sections "commented out" with a brief description of the use case.
This provides an obvious location and a reminder to add verification step(s) where possible (Results) and to indicate what procedure (if any) the user should consider next.

**Comment by mishaone** [comment]
+1 to results/verification but I'm unsure about Next Steps. The benefit of next steps would ideally be cross links, AFAIK, and we want to avoid those, so perhaps it's better to just remove the next steps part altogether? Ideally, the modules should be standalone so there shouldn't really be any mandatory next steps, just options for them based on which assembly it's being used in at the moment. Thoughts?

**Comment by JStickler** [comment]
Perhaps put the "next steps" in the assembly file?  I know that I've written installation instructions where you install the software, verify that it works, but can't actually use it until you perform some configuration steps or create records that aren't actually part of the installation, but more initial (day one) tasks.  I wouldn't group the two separate tasks into the same assembly, as they might be performed by different users, but I would definitely make a note that you have to do X next before you can do anything else.

**Comment by tylerkelly13** [comment]
So, I'll create a PR with the optional 'results' section in the template and guide, but 'next steps' should probably just be mentioned in the modular docs guide and not added to the template due to the limited use-cases for it.
Sound good?

**Comment by mishaone** [comment]
I'm not sure that Next Steps should be in a module at all. If something is always done after another procedure, it's probably best to include it in in that one procedure. If it's not always done, having *Next Steps* that may not be relevant to all use cases limits the module reuse and independence. I'd vote for removing next steps altogether and using the assembly to indicate what the next step should be (by plaing the next step module after the current one).

**Comment by trichard10** [comment]
I'd prefer something more like "Verification" as a title, instead of "Results". Results can end up more like "You created a thing, and it is now in the place", which is largely useless, whereas verification suggests that you're doing something to check that your thing worked.

**Comment by tylerkelly13** [comment]
Verification or Verify ?

**Comment by mishaone** [comment]
Maybe **Verification steps** to make it clear that these are the steps to verify what you've done in the procedure.

**Comment by tylerkelly13** [comment]
Added draft changes in PR #76 .
Feel free to suggest/discuss/make changes.

**Comment by adahms** [comment]
@JStickler @sjay72 @bhardesty @ncbaratta @finp - In the interest of moving this one forward, it looks like there are two directions we can take based on the ideas proposed -

1. Accept the PR as Tyler has submitted it, including the new optional step and providing guidance about verification there.
2. Abandon the idea of including an optional step as originally proposed and taking the approach @sjay72 has recommended, telling users what they will achieve at the beginning of the procedure.

I can see an argument for both, but the minimalist nature of @sjay72's suggestion appeals to me. But even if we choose that direction, it would still seem like a good idea to add guidance along the lines that such verification information should be included in the opening paragraph.

Does anyone have any strong feelings either way?

**Comment by ncbaratta** [comment]
minimalism++ :)

**Comment by finp** [comment]
+1 to @sjay72 but just a note that in Integreatly web app [1], we are forced not just to write verification steps, but also 'what to do if the verification steps fail' :(

[1]

**Comment by adahms** [comment]
Closing this issue now that the associated PR has been merged.

**Comment by jherrman** [comment]
> Maybe **Verification steps** to make it clear that these are the steps to verify what you've done in the procedure.

A fairly minor quibble, but do we really need to call it "Verification *steps*"? After all, we don't say "Procedure steps" either, and IMO just "Verification" conveys the concept perfectly fine. So adding another word to the sub-heading feels counter-intuitive and counter-minimalist. Also, in my experience, more often than not it's just a single step, so blanket-using a plural phrase here makes it stylistically somewhat awkward.
