### ISSUE TITLE
Release Notes Template

### ISSUE THREAD

**Issue by tylerkelly13** [redhat-documentation/modular-docs#69]
Is a release notes template/guidelines within the scope of this project?

If we are publishing release notes through the same system, would we build them using the existing templates, or should we have a template for this?

Note: I think that we don't need a separate template, but I thought I should raise the question anyway. We should be trying to be more consistent in the format we use to provide a more consistent customer experience.

**Comment by JStickler** [comment]
I've been meaning to "modularize" the Release Notes template that I created as part of the release notes content model.  If someone else has time to do that, feel free!  You can find it here -> https://gitlab.cee.redhat.com/jstickle/template-release-notes

**Comment by ritz303** [comment]
I think any effort to modularize the release notes should consider that we already have an automated release notes builder call CoRN.  Marek Suchanek is leading the project, which can be found here:

- https://gitlab.cee.redhat.com/ccs-tools/corn/blob/master/README.adoc

I think many doc teams are using the CoRN script.  We (the Ceph docs team) are using this automation tool extensively, it saves us time and is easy to use.  The CoRN script does make use of templates.  So I suggest that you reach out to Marek and run this idea by him.

**Comment by ritz303** [comment]
Closing this issue because release notes are a special case, and are outside the scope of modular documentation at this time.
