### ISSUE TITLE
What License does it have?

### ISSUE THREAD

**Issue by ojn** [redhat-documentation/modular-docs#78]
This also relates to doc-guidelines, asciidoc-markup-conventions and community-collaboration-guide.

You have some good content here and I wanted to adopt some parts for https://pagure.io/fedora-docs/documentation-guide and somehow expected that this would maybe be CC-BY-SA. But since it doesn't state that anywhere I have to assume that it can't be adopted for reuse in other docs. I hope you can reconsider this.

**Comment by rkratky** [comment]
Good point. Red Hat uses CC-BY-SA for its downstream docs, so I believe we can safely assume this to be the right choice for these materials, too. I submitted a PR: #79.
