### ISSUE TITLE
anchor IDs not consistent

### ISSUE THREAD

**Issue by tobydrake7** [redhat-documentation/modular-docs#85]
The anchor IDs in the template files are not consistent.
The Assembly anchor and Concept anchor IDs have `-{context}`.
The Procedure and Reference anchor IDs have `_{context}`.

Examples from template files:
~~~
[id='a-collection-of-modules-{context}']
[id='concept-explanation-{context}']
[id='doing-one-procedure_{context}']
[id='reference-material_{context}']
~~~

**Comment by tobydrake7** [comment]
@sterobin My bad for not seeing that to begin with. I'm hoping that the underscore will win the day and move on using that in my files. If it gets changed, I'll change it back. Closing this now.

**Comment by sterobin** [comment]
@tobydrake7 Haha, I'm hoping that dashes will win for other reasons. Still friends? :) Thanks for the close eye Toby!

**Comment by tobydrake7** [comment]
@sterobin FFL buddy. I actually don't have a real preference. Underscores do have a way of becoming problematic for certain applications, so I'll go with dashes until such time as a different decision is made. I use dashes in all my command line variables, so there's that. Put my vote down for dashes! :)

**Comment by sterobin** [comment]
Wohoo! Better yet, @tobydrake7, put your vote down in #66. Eh, eh? :)

**Comment by tobydrake7** [comment]
Done.
