### ISSUE TITLE
IDs must use double quotes, not single quotes

### ISSUE THREAD

**Issue by mrksu** [redhat-documentation/modular-docs#87]
As it was explained to @VladimirSlavik by AsciiDoctor developers[1], IDs must always be surrounded by double quotes in AsciiDoc because single quotes are markup.

The problem manifests, for example, when there is a double dash in an ID:

- When written as `id="x--y`", everything works as expected, and the resulting ID is `x--y`.
- When written as `id='x--y'`, the double dash is converted to an en-dash (`x–y`), breaking the `ccutil` build.

Templates should be edited to replace single quotes with double quotes in ID.

[1] https://github.com/asciidoctor/asciidoctor/issues/2960

**Comment by VladimirSlavik** [comment]
I should add that such change would not break compatibility - the existing usage of single quotes is in no way affected.

There are more auto-replacements that could be applied as a surprise, not just double dash.

**Comment by kalexand-rh** [comment]
We merged #91, so this issue is fixed. Thanks!
